### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by YubaC** [Yuba-Technology/test#1]
### Prerequisites

- [X] I have validated my Python code to avoid common problems
- [X] I have [searched](https://github.com/Yuba-Technology/test/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/Yuba-Technology/test/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

1

### Minimal, Complete, and Verifiable Example

1

### What operating system are you seeing the problem on?

1

### What Python version are you using?

1

### Environment

1

### What version of Archives are you using?

1

**Comment by Begonia-Aquaphle** [comment]
Hi @YubaC! 👋
Thanks for opening this issue. We will get back to you soon.

**Comment by Begonia-Aquaphle** [comment]
Hello @YubaC. Bug reports must include a **live demo** of the issue. You can visit our [CONTRIBUTING.md](https://github.com/Yuba-Technology/test/blob/main/.github/CONTRIBUTING.md) for more information on how to create a live demo.
